install.packages("readxl")
pkmn <- readxl::read_excel(path="L:/BUT/SD/Promo 2025/amessaoudi/S2/Prog statistique/pokemon.xlsx", sheet="pokemon")
View(pkmn)
dim(pkmn)
ncol(pkmn)
nrow(pkmn)
summary(pkmn)
pkmn$is_legendary <- as.factor(pkmn$is_legendary)
pkmn$type <- as.factor(pkmn$type)
pkmn$generation <- as.factor(pkmn$generation)
summary(pkmn)
pkmn$attack_group <- ifelse(pkmn$attack>= median(pkmn$attack),"attack+", "attack-")
View(pkmn)
pkmn$attack_group <- as.factor(pkmn$attack_group)
summary(pkmn$attack_group)
pkmn$water_fire <- ifelse(pkmn$type %in% c("water","fire"), "yes", "no")
pkmn$water_fire <- as.factor(pkmn$water_fire)
View(pkmn)
pkmn$best <- ifelse(pkmn$attack > quantile(pkmn$attack, probs = 0.75) 
                    & pkmn$defense > quantile(pkmn$defense, probs = 0.75)
                    & pkmn$speed > quantile(pkmn$speed, probs = 0.75),"Yes","No")
pkmn$best <- as.factor(pkmn$best)
View(pkmn)
summary(pkmn$best)
requete <- subset(pkmn, !is.na(weight_kg))
View(requete)
pkmn$weight_kgNA <- ifelse(is.na(pkmn$weight_kg),median(pkmn$weight_kg,na.rm = TRUE),pkmn$weight_kg)
pkmn$pkmn_height_mNA <- ifelse(is.na(pkmn$height_m),median(pkmn$height_m, na.rm=TRUE),pkmn$height_m)
View(pkmn)
pkmn$weight_group <- cut(pkmn$weight_kg, breaks = 3, labels =c("Léger","Moyen","Lourd"))
pkmn$height_group <- cut(pkmn$height_m, breaks=c(0,1,2,3,max(pkmn$height_m, na.rm = TRUE)))
View(pkmn)
pkmn$defense_group <- cut(pkmn$defense, breaks = quantile(pkmn$defense, na.rm = TRUE), include.lowest = TRUE)
View(pkmn)                          
aggregate(x = attack~type, data = pkmn, FUN = function(x) mean(x))
aggregate(x = attack~type+generation, data = pkmn, FUN = function(x) mean(x))
aggregate(x = pokedex_number~type, data = pkmn, FUN = function(x) length(x))
aggregate(x = speed~generation+type, data = pkmn, FUN = function(x) c(mean(x), median(x), length(x)))
