df <- read.csv(file="C:/Users/amessaoudi/Downloads/velov.csv", header = TRUE, sep=";", dec=",")
View(df)
summary(df)
df$status <- as.factor(df$status)
df$CodePostal <- as.factor(df$CodePostal)
summary(df)
df$bornes <- ifelse(df$capacity != (df$bikes + df$stands),"KO", "OK")
View(df)
hist(df$capacity, main="Distribution de la capacité des stations")
hist(df$capacity, main="Distribution de la capacité des stations", breaks = 6)
hist(df$capacity, main="Distribution de la capacité des stations", breaks = 6,col="red")
hist(df$capacity, main="Distribution de la capacité des stations", breaks = 6,col="red", xlab="Capacity")
abline(h = 100, col = "blue", lty = 2)
hist(x = df$capacity, main = "Distribution de la capacité des stations",col = "red", probability = TRUE,xlab = "Capacity")
lines(density(df$capacity),lty = 2,col = "blue",lwd = 2)
hist(x = df$capacity, main = "Distribution de la capacité des stations",col = "red", probability = TRUE,xlab = "Capacity", ylim = c(0,0.8))
lines(density(df$capacity),lty = 2,col = "blue", lwd = 2)
boxplot(df$capacity, main = "Diagramme en boite de la capacité")
boxplot(df$capacity, main = "Diagramme en boite de la capacité", horizontal = TRUE)
boxplot(df$capacity, main = "Diagramme en boite de la capacité", horizontal = FALSE, outline = FALSE)
moy = mean(df$capacity, na.rm = TRUE)
points(moy, col="red", pch=15, cex = 2)
par(mfrow=c(1,2))
df7 <- subset(df, CodePostal == "69007")
boxplot(x = df7$bikes, main = "Boxplot nb vélos \n 69007",ylim = c(0,40))
df8 = subset(df, CodePostal == "69008")
boxplot(x = df8$bikes, main = "Boxplot nb vélos \n 69008",ylim = c(0,40))
par(mfrow=c(1,1))
boxplot(formula=bikes ~ bonus, data=df, main = "Dispo vélos par rapport aux stations bonus")
means <- tapply(X = df$bikes, INDEX = df$bonus, FUN = function(X) mean(X))
points(means, col = "red", pch = 19)
barplot(height = table(df$bonus), main = "Répartition du nombre de stations bonus")
barplot(height = table(df$bonus), main = "Répartition du nombre de stations bonus", horiz = TRUE)
effectif = table(df$bonus)
barplot(height = prop.table(effectif), main = "Répartition en pourcentage du nombre de stations bonus", horiz = TRUE)
effectif = table(df$banking, df$bonus)
print(effectif)
barplot(height = effectif,main = "Bonus vs Banking",xlab = "Station Bonus ?")
frequence = prop.table(x = effectif)
barplot(height = frequence,main = "Bonus vs Banking",xlab = "Station Bonus ?",col = c("red","green"))
legend_labels <- colnames(frequence)
legend(x = "topright", legend = legend_labels, fill  = c("red","green"))
frequence = prop.table(x = effectif, margin = 2)
barplot(height = frequence,main = "Bonus vs Banking",xlab = "Station Bonus ?",col = c("red","green"))
legend_labels <- colnames(frequence)
legend(x = "topright", legend = legend_labels, fill  = c("red","green"))
frequence = prop.table(x = effectif, margin = 2)

barplot(height = frequence,main = "Bonus vs Banking",xlab = "Station Bonus ?",col = c("red","green"),beside = TRUE)
legend_labels <- colnames(frequence)
legend(x = "topright", legend = legend_labels, fill  = c("red","green"))
pie(x = effectif,
main = "Répartition du nombre \n de station bonus",col = c("yellow","green"))
effectif = table(df$CodePostal)
top10 = sort(effectif, decreasing = TRUE)[1:10]
barplot(height = top10,main = "Top 10 du nombre de station",col = palette(),las = 2)
barplot(height = top10,main = "Top 10 du nombre de station",col = colors(),las = 2)  
print(colors())
dev.print(device = png, file = "export.png", width = 600)
plot(x=df$stands, y =df$capacity, main = "Corrélation places disponibles/ capacité", xlim = c(0,60), ylim = c(0,60), pch=19)
df$bornes = as.factor(df$bornes)
plot(x=df$stands, y =df$capacity, main = "Corrélation places disponibles/ capacité", xlim = c(0,60), ylim = c(0,60),col = df$bornes, pch=19)
legend("topright", legend = levels(df$bornes),col = palette(), pch = 19)
myColors <- c("red", "blue", "green")
plot(x=df$stands, y =df$capacity, main = "Corrélation places disponibles/ capacité", xlim = c(0,60), ylim = c(0,60),col = myColors[df$bornes], pch=19)
legend("topright", legend = levels(df$bornes),col = palette(), pch = 19)
moy_stands = mean(df$stands)
moy_capacity = mean(df$capacity)
points(x = moy_stands,y = moy_capacity, pch = 15,col = myColors[3], cex = 2)


library(leaflet)
library(dplyr)
library(ggplot2)

# Créer une carte Leaflet
leaflet(df) %>% 
  addTiles() %>% 
  addMarkers(
    ~position_longitude,
    ~position_latitude, 
    popup = ~address,
    clusterOptions = markerClusterOptions()
  )
