iris
class(iris)
View(iris)
nrow(iris)
ncol(iris)
colnames(iris)
summary(iris)
iris[,c("Sepal.Length", "Species")]
iris[c(100, 103, 105),]
iris[c(50:100),]
mean(iris$Sepal.Length)
median(iris$Sepal.Width)
sd(iris$Petal.Length)
quantile(iris$Petal.Width, probs = seq(from=0.1, to=0.9, by=0.1))
dfmanga <- read.csv("C:/Users/amessaoudi/Downloads/manga.csv", header = TRUE, dec=".", sep = ",")
dfanime <- read.csv("C:/Users/amessaoudi/Downloads/anime.csv", header = TRUE, dec=".", sep = ",")
class(dfmanga)
class(dfanime)
View(dfmanga)
View(dfanime)
dim(dfmanga)
dim(dfanime)
mean(dfmanga$Score)
mean(dfanime$Score)
sum(dfmanga$Vote)
sum(dfanime$Vote)
sd(dfmanga$Score)
sd(dfanime$Score)
quantile(dfmanga$Score, probs = seq(from=0.1, to=0.9, by=0.1))
quantile(dfanime$Score, probs = seq(from=0.1, to=0.9, by=0.1))
sup9 <- subset(dfmanga, Score > 9) 
nrow(sup9)
nbvote <- subset(dfmanga, Vote>=200000)
nrow(nbvote)
votenote <- subset(dfmanga, Vote>=200000 & Score>8)
nrow(votenote)
note <- subset(dfmanga, Score>=7 & Score<=8)
nrow(note)
effectif <- table(dfanime$Rating)
print(effectif)
length(effectif)
prop.table(effectif)
rating17 <- subset(dfanime, Rating =="R - 17+ (violence & profanity)")
nrow(rating17)
rating17note <- subset(dfanime, Rating =="R - 17+ (violence & profanity)" & Score>8)
nrow(rating17note)
norating17 <- subset(dfanime, Rating !="R - 17+ (violence & profanity)")
nrow(norating17)
ratingchildren <- subset(dfanime, Rating %in% c("PG - Children", "G - All Ages"))
nrow(ratingchildren)
noratingchildren <- subset(dfanime, !Rating %in% c("PG - Children", "G - All Ages"))
nrow(noratingchildren)
notevoteanime <- subset(dfanime, Score>9 | Vote>400000)
nrow(notevoteanime)
dfanime <- dfanime[,c("Title", "Score", "Vote", "Ranked")]
View(dfanime)
dfmanga <- dfmanga[,c("Title", "Score", "Vote", "Ranked")]
View(dfmanga)
dfanime$Type <- "Anime"
dfmanga$Type <- "Manga"
View(dfmanga)
dfconcat <- rbind(dfmanga, dfanime)
View(dfconcat)
write.table(dfconcat, file = "ExportTp1.csv", sep=",", row.names = FALSE)
