df <- read.csv(file="L:/BUT/SD/Promo 2025/amessaoudi/S2/Prog statistique/fao.csv", sep=";", dec=",", header = TRUE)
nrow(df)
summary(df)
mean(df$Dispo_alim, na.rm=TRUE)
sum(df$Population, na.rm= TRUE)
sd(df$Export_viande, na.rm = TRUE)
sd(df$Import_viande, na.rm = TRUE)
median(df$Prod_viande, na.rm = TRUE)
quantile(df$Dispo_alim)
quantile(df$Dispo_alim, seq(0,1,0.01))
ordre = order(df$Population)
moinspeup = head(df[ordre, ], n=5)
View(moinspeup)
ordre2 = order(df$Population, decreasing = TRUE)
pluspeup = head(df[ordre2, ], n=5)
View(pluspeup)
ordre3 = order(df$Prod_viande, decreasing = TRUE)
plusviande = head(df[ordre3, ], n=5)
View(plusviande)
ordre4 = order(df$Import_viande, decreasing = TRUE)
importviande = head(df[ordre4, ], n=5)
View(importviande)
supmoy = subset(df, Dispo_alim>=2300)
View(supmoy)
dispoimport = subset(df, Dispo_alim > 3500  & Import_viande > 1000)
View(dispoimport)
frabel = subset(df, Nom %in% c("France","Belgique"))
View(frabel)
df$part_export<-df$Export_viande/df$Prod_viande
df$dispo_alim_pays<-df$Dispo_alim*df$Population
write.table(x = df, file = "ExportTp2.csv")
total <- sum(df$dispo_alim_pays, na.rm = TRUE)
print(total)
nb_pers <- total/2300
print(nb_pers)
plot(x = df$Prod_viande,
     y = df$Export_viande, 
     main = "Pays : Prod_viande / Export_viande")
cor(x = df$Prod_viande,
    y = df$Export_viande, use = "complete.obs")
matriceCor = cor(df[ , - 1] , use = "complete.obs")
matriceCor = round(matriceCor , 2)
View(matriceCor)
install.packages("corrplot")
library(corrplot) 
corrplot(matriceCor, method="circle")
